решение задач занятия 1
js-tasks-ru/jsbasic-20210621_gladyscheva-dasha pull request #2
Opened 2021-06-26 11:22 UTC by gladdaria

2021-06-26 11:22 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-06-27 12:54 UTC, SinimaWath requested changes

2021-06-27 12:54 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  } return false;
Давай попробуем написать код без if, а сразу в одну строчку: `return !!name && ...`

2021-06-27 12:54 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  let lowerStr = str.toLowerCase();
так как loweStr ты не изменяешь, то это const

2021-06-27 15:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-06-27 17:35 UTC, SinimaWath approved these changes

2021-06-27 17:35 UTC, merged