задачи 1 и 2 занятия 5
js-tasks-ru/jsbasic-20210621_gladyscheva-dasha pull request #8
Opened 2021-07-27 04:19 UTC by gladdaria

2021-07-27 04:20 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-27 19:47 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-29 14:44 UTC, SinimaWath requested changes

2021-07-29 14:44 UTC, SinimaWath commented on 5-module/3-task/index.js
> +  let i = 0;
i - немного непонятное название переменной, оно не говорит о том, что в ней находится ( Давай попробуем назвать как-то по другому

2021-07-29 15:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-07-29 16:46 UTC, SinimaWath approved these changes

2021-07-29 16:46 UTC, merged